### ISSUE TITLE
How to make available in zed?

### ISSUE THREAD

**Issue by fdncred** [zed-extensions/nu#3]
How do we make this extension available in zed extensions dialog?

**Comment by JosephTLyons** [comment]
Hey @fdncred, can you give a bit more detail of what you are looking for? If you are looking for how to add an extension to the extension suggestion mechanism, you can do that here:

- https://github.com/zed-industries/zed/blob/3289188e0adaa6c6e73836f8beef5abad3982376/crates/extensions_ui/src/extension_suggest.rs#L16

**Comment by fdncred** [comment]
Hey @JosephTLyons, sorry I wasn't clear. This is what I'm talking about. This extension for nushell is now at version 0.0.3. If you bring up zed and go to the extensions window, you only see version 0.0.1. I want to know how to make version 0.0.3 show up in zed so I can install it.

**Comment by JosephTLyons** [comment]
Hey @fdncred, we were blocked on that [NU extension PR](https://github.com/zed-industries/extensions/pull/104/files/fae5f5b52f4f5fd3ef44d40db1121b56bae94275..0db2d16a0cf2940564f54a982382ec5c1e06d163), but it looks like Max fixed it and now the extension store is reporting that nu v0.0.2 is in:

<img width="865" alt="SCR-20240415-npgw" src="https://github.com/zed-extensions/nu/assets/19867440/e275ebb5-8dd4-4792-b43e-70cb18415960">

You need to bump the version in the [extensions repo](https://github.com/zed-industries/extensions) as well as adjust the nu plugin submodule to point to the main commit - same as what I did in this commit:

- https://github.com/zed-industries/extensions/pull/104

**Comment by JosephTLyons** [comment]
I bumped things in this repo to use the newest zed_extension_api and bumped the `nu` extension version:

https://github.com/zed-extensions/nu/pull/4

I then updated the `extensions` repo to point to the newest items in this repo:

https://github.com/zed-industries/extensions/pull/550

**Comment by fdncred** [comment]
so many places to update things. not sure i'm digging this or know how to update it in the future.

**Comment by fdncred** [comment]
@JosephTLyons What does this mean, "Incompatible"? And how do we make it compatible?
![Screenshot 2024-04-15 at 7 21 27 PM](https://github.com/zed-extensions/nu/assets/343840/049d45cb-9845-4c98-8ec5-8811459cbfb2)

**Comment by JosephTLyons** [comment]
Oh yeah, this happens because the newest API version being used by the extension hasn't yet trickled into the release builds.  Once that happens, it will download.  That should be happening very soon, but I guess I should've asked you if you needed to release anything else between now and then, since we are now blocked until those changes trickle into Preview and then Stable. Sorry about that! I should get you onto the nightly build, so you can have access to extension changes right away.

**Comment by JosephTLyons** [comment]
The extension API should be stabilizing and bumped less often going forward, so I don't think this will be a thing we encounter often.

**Comment by fdncred** [comment]
ok, i can wait. does zed update extensions automatically. like if i had 0.0.1 installed and 0.0.3 comes out, will it update to 0.0.3 automatically?

**Comment by JosephTLyons** [comment]
> ok, no worries. i can wait. does zed update extensions automatically. like if i had 0.0.1 installed and 0.0.3 comes out, will it update to 0.0.3 automatically?

We do auto updates when opening the editor. You can manually update as well in the extension view.

**Comment by JosephTLyons** [comment]
> so many places to update things. not sure i'm digging this or know how to update it in the future.

I don't think it'll always be this complex.  I don't mind bumping the version in the extension store, once you land new things in here, if you want to ping me.

**Comment by JosephTLyons** [comment]
Also, now that we are getting to a point of stopping (for awhile) on extensions, we will put out some blog posts and documentation to make this process more clear.
